version: 0.2
env:
  REACT_APP_ENDPOINT: ""
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -f
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cp .env.development .env.production.local
  build:
    commands:
      - echo Build started on `date`      
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
    - './node_modules/**/*'